name: spaceapps-challenge
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - iris
  - xarray
  - cfgrib
  - iris-grib
  - cartopy
  - pandas
  - numpy
  - matplotlib
  - scipy
  - cf-units
  - ipykernel
  - ipython
  - nc-time-axis
  - cdflib
  - pip
  - pip:
    - spacepy
