name: spaceapps-challenge
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - xarray
  - pandas
  - numpy
  - matplotlib
  - scipy
  - ipykernel
  - ipython
  - pytorch
  - pytorch-lightning>=1.6
  - scikit-learn
  - cdflib
  - pip
  - pip:
    - spacepy
