name: spaceapps-challenge
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - iris
  - xarray
  - pandas
  - numpy
  - matplotlib
  - scipy
  - ipykernel
  - ipython
  - cdflib
  - pip
  - pip:
    - spacepy
